name: macChrome
on: [push]
jobs:
  chrome-on-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome

      - name: Slack Notification
      - uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}           
