name: "main"
on: [push]
jobs:
  dangerjs-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Danger
      uses: danger/danger-js@9.1.6
      env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}