name: main
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Danger JS
        uses: danger/danger-js@master
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        with:
          args: --dangerfile .ci/danger/dangerfile.js        