name: ubuntuFirefox
on: push
jobs:
  firefox:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node12.16.1-chrome80-ff73
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          browser: chrome
