name: ubuntuChrome
on: [push]
jobs:
  chrome-on-ubuntu:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_URL: docker.pkg.github.com
      IMAGE_NAME: ${{ github.repository }}/cypress_cucumber
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: '#workflows'
        if: always()
      - name: Checkout
        uses: actions/checkout@v2
      - name: Variables
        id: vars
        run: echo "::set-output name=SHORT_COMMIT_ID::$(git rev-parse --short HEAD)"
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#workflows'
        if: always()  
#       - name: Slack Notification
#         uses: rtCamp/action-slack-notify@master
#         env:
#           SLACK_CHANNEL: general
#           SLACK_COLOR: '#3278BD'
#           SLACK_ICON: https://github.com/rtCamp.png?size=48
#           SLACK_MESSAGE: 'Post Content :rocket:'
#           SLACK_TITLE: Post Title
#           SLACK_USERNAME: rtCamp
#           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
