name: windowsEdge
on: [push]
jobs:
  tests:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress info
        uses: ./
        with:
          build: npm run info
          working-directory: examples/chrome
          browser: edge